apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceb1
  namespace: pair
  labels:
    app: serviceb
    version: serviceb1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceb
      version: serviceb1

  template:
    metadata:
      labels:
        app: serviceb
        version: serviceb1

    spec:
      containers:
        - name: serviceb
          image: hokunpark/custom2:serviceB
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          ports:
            - containerPort: 11001
          command: ["uvicorn"]
          args:
            [
              "main:app",
              "--host",
              "0.0.0.0",
              "--port",
              "11001",
              "--workers",
              "1",
              "--loop",
              "uvloop",
              "--http",
              "httptools",
            ]

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceb2
  namespace: pair
  labels:
    app: serviceb
    version: serviceb2

spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceb
      version: serviceb2

  template:
    metadata:
      labels:
        app: serviceb
        version: serviceb2

    spec:
      containers:
        - name: serviceb
          image: hokunpark/custom2:serviceB
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          ports:
            - containerPort: 11001
          command: ["uvicorn"]
          args:
            [
              "main:app",
              "--host",
              "0.0.0.0",
              "--port",
              "11001",
              "--workers",
              "1",
              "--loop",
              "uvloop",
              "--http",
              "httptools",
            ]

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceb3
  namespace: pair
  labels:
    app: serviceb
    version: serviceb3

spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceb
      version: serviceb3

  template:
    metadata:
      labels:
        app: serviceb
        version: serviceb3

    spec:
      containers:
        - name: serviceb
          image: hokunpark/custom2:serviceB
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          ports:
            - containerPort: 11001
          command: ["uvicorn"]
          args:
            [
              "main:app",
              "--host",
              "0.0.0.0",
              "--port",
              "11001",
              "--workers",
              "1",
              "--loop",
              "uvloop",
              "--http",
              "httptools",
            ]

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceb4
  namespace: pair
  labels:
    app: serviceb
    version: serviceb4

spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceb
      version: serviceb4

  template:
    metadata:
      labels:
        app: serviceb
        version: serviceb4

    spec:
      containers:
        - name: serviceb
          image: hokunpark/custom2:serviceB
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          ports:
            - containerPort: 11001
          command: ["uvicorn"]
          args:
            [
              "main:app",
              "--host",
              "0.0.0.0",
              "--port",
              "11001",
              "--workers",
              "1",
              "--loop",
              "uvloop",
              "--http",
              "httptools",
            ]

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker4

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceb5
  namespace: pair
  labels:
    app: serviceb
    version: serviceb5

spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceb
      version: serviceb5

  template:
    metadata:
      labels:
        app: serviceb
        version: serviceb5

    spec:
      containers:
        - name: serviceb
          image: hokunpark/custom2:serviceB
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          ports:
            - containerPort: 11001
          command: ["uvicorn"]
          args:
            [
              "main:app",
              "--host",
              "0.0.0.0",
              "--port",
              "11001",
              "--workers",
              "1",
              "--loop",
              "uvloop",
              "--http",
              "httptools",
            ]

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceb6
  namespace: pair
  labels:
    app: serviceb
    version: serviceb6

spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceb
      version: serviceb6

  template:
    metadata:
      labels:
        app: serviceb
        version: serviceb6

    spec:
      containers:
        - name: serviceb
          image: hokunpark/custom2:serviceB
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          ports:
            - containerPort: 11001
          command: ["uvicorn"]
          args:
            [
              "main:app",
              "--host",
              "0.0.0.0",
              "--port",
              "11001",
              "--workers",
              "1",
              "--loop",
              "uvloop",
              "--http",
              "httptools",
            ]

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceb7
  namespace: pair
  labels:
    app: serviceb
    version: serviceb7

spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceb
      version: serviceb7

  template:
    metadata:
      labels:
        app: serviceb
        version: serviceb7

    spec:
      containers:
        - name: serviceb
          image: hokunpark/custom2:serviceB
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          ports:
            - containerPort: 11001
          command: ["uvicorn"]
          args:
            [
              "main:app",
              "--host",
              "0.0.0.0",
              "--port",
              "11001",
              "--workers",
              "1",
              "--loop",
              "uvloop",
              "--http",
              "httptools",
            ]

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker5
