apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config-worker3
  namespace: monitoring
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: [ "HTTP/1.1", "HTTP/2" ]
          valid_status_codes: []
          method: GET
          fail_if_ssl: false
          fail_if_not_ssl: false
          tls_config:
            insecure_skip_verify: false
      icmp:
        prober: icmp
        timeout: 5s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter-worker3
  namespace: monitoring
  labels:
    app: blackbox-exporter-worker3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter-worker3
  template:
    metadata:
      labels:
        app: blackbox-exporter-worker3
    spec:
      containers:
      - name: blackbox-exporter
        image: prom/blackbox-exporter:latest
        args:
        - "--config.file=/config/blackbox.yml"
        volumeMounts:
        - name: config-volume
          mountPath: /config
        ports:
        - containerPort: 9115
          name: http
      volumes:
      - name: config-volume
        configMap:
          name: blackbox-exporter-config-worker3
      nodeSelector:
        kubernetes.io/hostname: worker3
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter-worker3
  namespace: monitoring
spec:
  selector:
    app: blackbox-exporter-worker3
  ports:
    - protocol: TCP
      port: 9115
      targetPort: 9115