apiVersion: v1
kind: Service
metadata:
  name: serviced
  namespace: pair
spec:
  selector:
    app: serviced
  ports:
    - name: http
      port: 11003
      targetPort: 11003
  type: ClusterIP
  sessionAffinity: None
