apiVersion: v1
kind: Service
metadata:
  name: servicee
  namespace: pair
spec:
  selector:
    app: servicee
  ports:
    - name: http
      port: 11004
      targetPort: 11004
  type: ClusterIP
  sessionAffinity: None
